(() => {
  'use strict';
  const STORAGE_KEY = 'jocelyn-romeo-wedding-budget-v1';
  const weddingDate = '2027-01-23';
  const seed = {
    budgets: [
      ['Catering','RCL Catering Services',50000,2000],['Florist','Maestro Events',15000,0],['Cake','Zue Bakeshop',3500,0],['Photo / Video',"D'Onin Films and Photography",30000,2000],['Hair and Makeup','Eugene Ermita',13000,0],['Wedding Gown','',20000,0],["Groom's Barong / Attire",'',10000,0],['Invitation','',2000,0],['Souvenir','',10000,0],['Wedding Coordinator','Maestro Events',16000,0],['Principal Sponsor Souvenir','',0,0],['Secondary Sponsor Souvenir','',0,0],['Flower Girls and Boys Souvenir','',0,0],['Wedding Giveaways','',5000,0],['Pigs / Feeds (Biik)','',100000,0],['Pagsasabi sa Ninong / Ninang','',12000,0],['Rekados / Ingredients','',70000,0],['Church','Lian Church',7500,0],['Wedding Ring','',20000,0],['Pre-nup Venue','Warm Cafe Tuy',5000,1000],['Pre-nup Outfit','',0,0]
    ].map((x,i)=>({id:'b'+(i+1),item:x[0],supplier:x[1],amount:x[2],paid:x[3]})),
    transactions: [
      ['in','Bride',10000,'2026-03-21','March 2026'],['in','Groom',50000,'2026-03-21','March 2026'],['in','Bride',20000,'2026-03-22','April 2026'],['in','Groom',5918,'2026-03-22','April 2026'],['in','Bride',20000,'2026-03-23','May 2026'],['in','Groom',20000,'2026-03-23','May 2026'],['in','Bride',30000,'2026-03-21','June 2026'],['in','Bride',50000,'2026-05-13','July 2026'],['in','Bride',50000,'2026-07-07','August 2026'],['in','Bride',50000,'2026-07-02','September 2026'],
      ['out','Pamamanhikan',19000,'2026-03-21','Wedding expense'],['out','DP for Catering',2000,'2026-03-21','Catering'],['out','DP for Photographer',2000,'2026-03-21','Photo / Video'],['out','Gin at Hire ng chair at table',1050,'2026-03-22','Wedding expense'],['out',"Romeo's Kumpil",2550,'2026-03-23','Wedding expense'],['out','Biik',35000,'2026-05-13','Pigs / Feeds (Biik)'],['out','Feeds',3250,'2026-07-07','Pigs / Feeds (Biik)'],['out','Feeds',4875,'2026-07-02','Pigs / Feeds (Biik)'],['out','Feeds',3203,'2026-07-15','Pigs / Feeds (Biik)'],['out','Feeds',3800,'2026-07-25','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-07-27','Pigs / Feeds (Biik)'],['out','Ultima (Meds)',1150,'2026-08-07','Pigs / Feeds (Biik)'],['out','Ultima (Meds)',2300,'2026-08-07','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-08-12','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-08-12','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-08-19','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-08-24','Pigs / Feeds (Biik)'],['out','Feeds',3175,'2026-09-01','Pigs / Feeds (Biik)']
    ].map((x,i)=>({id:'t'+(i+1),type:x[0],title:x[1],amount:x[2],date:x[3],note:x[4]}))
  };
  let state = loadState(), txnFilter='all', deferredInstallPrompt=null;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const peso=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(n)||0);
  const dateText=s=>{const [y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)));};
  const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved?.budgets&&saved?.transactions)return saved;}catch(e){}return JSON.parse(JSON.stringify(seed));}
  function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function sums(){const totalIn=state.transactions.filter(t=>t.type==='in').reduce((a,t)=>a+t.amount,0),totalOut=state.transactions.filter(t=>t.type==='out'&&t.affectsFund!==false).reduce((a,t)=>a+t.amount,0),contractTotal=state.budgets.reduce((a,b)=>a+b.amount,0),contractPaid=state.budgets.reduce((a,b)=>a+b.paid,0);return{totalIn,totalOut,remaining:totalIn-totalOut,contractTotal,contractPaid,contractBalance:contractTotal-contractPaid};}
  function render(){const s=sums();$('#remainingMoney').textContent=peso(s.remaining);$('#totalIn').textContent=peso(s.totalIn);$('#totalOut').textContent=peso(s.totalOut);$('#contractTotal').textContent=peso(s.contractTotal);$('#contractPaid').textContent=`${peso(s.contractPaid)} paid so far`;$('#contractBalance').textContent=peso(s.contractBalance);const gap=s.remaining-s.contractBalance;$('#fundGap').textContent=(gap>=0?'+':'−')+peso(Math.abs(gap));$('#fundGapNote').textContent=gap>=0?'Current fund covers outstanding supplier balances':'More funding needed to cover current contracts';const pct=s.totalIn>0?Math.max(0,Math.min(100,(s.remaining/s.totalIn)*100)):0;$('#fundRing').style.setProperty('--pct',pct.toFixed(0));$('#fundPct').textContent=`${pct.toFixed(0)}%`;renderBudgets();renderTransactions();populateCategories();renderCountdown();}
  function budgetHTML(b){const spent=Math.min(b.paid,b.amount),pct=b.amount>0?Math.min(100,(spent/b.amount)*100):0;return `<div class="budget-row"><div><div class="budget-title">${escapeHtml(b.item)}</div><div class="budget-sub">${escapeHtml(b.supplier||'No supplier yet')}</div><div class="progress"><span style="width:${pct}%"></span></div><div class="budget-meta"><span>${peso(b.paid)} paid</span><span>${pct.toFixed(0)}%</span></div></div><div class="budget-money">${peso(b.amount)}</div></div>`;}
  function renderBudgets(){const sorted=[...state.budgets].sort((a,b)=>b.amount-a.amount);$('#budgetList').innerHTML=sorted.slice(0,6).map(budgetHTML).join('')||'<div class="empty">No budget items yet.</div>';$('#allBudgetList').innerHTML=sorted.map(budgetHTML).join('')||'<div class="empty">No budget items yet.</div>';}
  function renderTransactions(){const tx=[...state.transactions].filter(t=>txnFilter==='all'||t.type===txnFilter).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)).slice(0,24);$('#transactionList').innerHTML=tx.map(t=>`<div class="transaction"><div class="txn-icon ${t.type}">${t.type==='in'?'＋':'−'}</div><div><div class="txn-title">${escapeHtml(t.title)}</div><div class="txn-sub">${dateText(t.date)}${t.note?' · '+escapeHtml(t.note):''}</div></div><div class="txn-amount ${t.type}">${t.type==='in'?'+':'−'}${peso(t.amount)}</div></div>`).join('')||'<div class="empty">No transactions in this view.</div>';}
  function populateCategories(){const sel=$('#expenseCategory'),val=sel.value;sel.innerHTML='<option value="Wedding expense">Wedding expense</option>'+state.budgets.map(b=>`<option value="${escapeAttr(b.item)}">${escapeHtml(b.item)}</option>`).join('');if([...sel.options].some(o=>o.value===val))sel.value=val;}
  function renderCountdown(){const target=new Date(weddingDate+'T00:00:00+08:00'),days=Math.ceil((target-Date.now())/86400000);$('#countdown').textContent=days>0?`· ${days} days to go!`:days===0?'· Wedding day!':'· Happily married ♡';}
  function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600);}
  function celebrate(type='in'){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const layer=$('#celebrationLayer'),palette=type==='in'?['#6b0f2a','#b65c76','#f4d8df','#d6b36a','#fff5f7']:['#6b0f2a','#8f2847','#d8a8b5','#f2cbd4'];for(let i=0;i<(type==='in'?46:24);i++){const e=document.createElement('i');e.className=type==='in'?'confetti':'petal';e.style.left=(Math.random()*100)+'vw';e.style.background=palette[Math.floor(Math.random()*palette.length)];e.style.setProperty('--drift',((Math.random()-.5)*180)+'px');e.style.animationDelay=(Math.random()*.25)+'s';e.style.animationDuration=(1.2+Math.random()*1.1)+'s';layer.appendChild(e);setTimeout(()=>e.remove(),2600);}if(type==='out'){const hero=$('.hero-card');hero.classList.remove('pulse-deduct');void hero.offsetWidth;hero.classList.add('pulse-deduct');}}
  async function maybeNotify(title,body){if(!('Notification'in window)||Notification.permission!=='granted')return;try{if(navigator.serviceWorker?.ready){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'icon.svg',tag:'wedding-budget'});}else new Notification(title,{body});}catch(e){}}
  function closeDialog(d){if(d.open)d.close();}function setToday(){const today=new Date(),v=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');$$('input[type=date]').forEach(i=>{if(!i.value)i.value=v;});}function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}function escapeAttr(v){return escapeHtml(v).replace(/'/g,'&#39;');}
  $$('[data-open]').forEach(b=>b.addEventListener('click',()=>{setToday();$('#'+b.dataset.open).showModal();}));$$('.modal .close').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));$$('.modal').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));$('#showAllBudgets').addEventListener('click',()=>$('#budgetsModal').showModal());
  $('#moneyInForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),amount=Number(fd.get('amount'));if(!(amount>0))return showToast('Enter an amount greater than ₱0.');state.transactions.push({id:uid('t'),type:'in',title:String(fd.get('person')),amount,date:String(fd.get('date')),note:String(fd.get('note')||'Contribution')});saveState();render();closeDialog($('#moneyInModal'));e.currentTarget.reset();showToast(`Yay! ${peso(amount)} added to the wedding fund 💕`);celebrate('in');maybeNotify('Wedding fund updated 🎉',`${peso(amount)} was added. Keep going, you two!`);});
  $('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),amount=Number(fd.get('amount'));if(!(amount>0))return showToast('Enter an amount greater than ₱0.');const category=String(fd.get('category')||'Wedding expense');state.transactions.push({id:uid('t'),type:'out',title:String(fd.get('item')),amount,date:String(fd.get('date')),note:category});const b=state.budgets.find(x=>x.item===category);if(b)b.paid=Math.min(b.amount,Math.max(0,b.paid+amount));saveState();render();closeDialog($('#expenseModal'));e.currentTarget.reset();showToast(`${peso(amount)} deducted and safely tracked.`);celebrate('out');});
  $('#budgetForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),amount=Math.max(0,Number(fd.get('amount'))||0),paid=Math.max(0,Number(fd.get('paid'))||0),item=String(fd.get('item')).trim();if(!item)return showToast('Add a budget item name.');const existing=state.budgets.find(b=>b.item.toLowerCase()===item.toLowerCase());if(existing){existing.supplier=String(fd.get('supplier')).trim();existing.amount=amount;existing.paid=Math.min(paid,amount||paid);}else state.budgets.push({id:uid('b'),item,supplier:String(fd.get('supplier')).trim(),amount,paid:Math.min(paid,amount||paid)});saveState();render();closeDialog($('#budgetModal'));e.currentTarget.reset();showToast(`${item} budget saved! 🎉`);celebrate('in');maybeNotify('Budget item saved 💍',`${item}: ${peso(amount)}`);});
  $$('.chip').forEach(c=>c.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');txnFilter=c.dataset.filter;renderTransactions();}));
  $('#notifyBtn').addEventListener('click',async()=>{if(!('Notification'in window))return showToast('Device notifications are not available in this browser.');const p=await Notification.requestPermission();showToast(p==='granted'?'Notifications enabled! 🎉':'Notifications were not enabled.');if(p==='granted')maybeNotify('Wedding budget notifications are on 💕','We’ll celebrate when you add money or a budget item.');});
  $('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'Our Wedding Fund',exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`wedding-budget-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);showToast('Backup downloaded.');});
  $('#importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const j=JSON.parse(await f.text()),data=j.data||j;if(!Array.isArray(data.budgets)||!Array.isArray(data.transactions))throw new Error();state=data;saveState();render();showToast('Backup restored successfully.');}catch(err){showToast('That backup file could not be restored.');}e.target.value='';});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden');});window.addEventListener('appinstalled',()=>showToast('Installed! Your wedding fund is now on your home screen.'));
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();setToday();
})();